dist: trusty
sudo: false
language: node_js
node_js:
- '8'
addons:
  chrome: stable
  artifacts:
    debug: true
    paths:
    - ./__errorShots
    bucket: ci-results
    s3_region: ap-northeast-1
    secret:
      secure: SYaN2TZKNSca8CTE8FlKHAmRdO7ywuXNIbkzp7H2Jv6yM1lUjEnquhVEGtqoAGcGmVkHx9c7K6SUup75wNdtuth08KgkZ46X01gGNFES+M6FVBLsSHK2WRWgguPOisIz9YxQeFeX4LIG9scdKn+koYY3sSmNxFvdt/DR76cJlSMA1QNZ1q0yYBVOgAptqkckVexv7XqIEdMCXBw91gQtcdoMKhn6HKRe1GK6XDCU9gnv9kBQu7hfvMNzjGVdQuuCNYcGcaeYoWqK7azbH+3UQ0m+ECRGOZI/HPy/RjrloDhqziB2pas117FfLyGGoubmd84O6jVmY577JJsfBZZV9TdRG/5sHnyHrEhFHnoCwIguIx6f95TSDn8/swRc1a3uVwgjavDao6nJPDP/Zs0axIBPkTcTSDGASH8wAJx27IhlAs0/3mKwWPMzaoskmDBiU44j2XxsfM7Iid0zKfCyl/Dlk8pQvXnTrFQAcnErlfxwDe9VKXOvffyuZeL0xBHsi6tn8q/0RPx9ZssmMS46eBQroWR9AsE2YBSsPNPkF2AvUXIQVEBduAS3L6aZQDLnLz9T84I279+F20vQRJt4+EdD10YbH9oGe80B7BbNi9hvGJ7x2x27GKit6R2uiddtoQ6saIhQYc/BG7p0Yl7g9xoKUnjGa6ZSxBUIXgsp2Ns=
    key:
      secure: W+3KsIcS2YVxe6HNaeyD4t9gOt/+Tl5s0onsvaKwlKOJTA3MMPaqJlxKwRh8ddW4KrZlN0UvdqmcF4cTwcTUoRvnJM7ErELzpRrGHmeF4j49tn4tNS21PDKY5mTTKZ1o4yGQy7jeoYVoaRXKwGDD6bEtvaQ/m35xTJRoYwuvz2NAey03K5VSmAXhx1Dkfh5iT1eBIGcn94wrTFrYie8qS0ADS6GLMhE+h4yvjpf0RnKuaDe+sqrbnkMm2xsqISN5nVKop1yR8rE0dMWaBRw0OGC4V1NghNqRPTTGfmH/pa5LfrRL9Ka6aFnoUbJ3Lkm5Bh7Q15W7C39+lDPTZLXznMwPbvZpJnfF/T5apNrb080TiTUSQgt2tgGAryJjbh/ivZoK9qkdYx7HR78n2jiSP98cMfMrstAIF3M2RnP0pGScSVhN3Prp8I/NoJgRpFauqVQc50pxlvxedNpSwGhlT4rnaGbqhwZSA7ZfQebATpnehIoVjpZHkuNWgWK1bg4J34HOknLZBZy/ZFKkUunCcT3J8oXOUeZg3I//FzINWXgXFNzDrmZ9F6C4SRDSynr+nMfroQPKZBwDi+SS+ycvQhnFZ/XQitrMMc/4j1TGCMp0vquFG3LznLA3x9l0uguPmX3n7RY7bAXROehBQaPcRkg3zAib3qxt6wIeFzjEdvY=
install:
- wget https://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- npm install
script:
- npm run build
- npm test
notifications:
  slack:
    secure: dJr827OKb0wZgq/cX8C06PzxcTho1kyDkD5gtq3FWyN8i+0pa52jV22MHYMhbKl/Er7Tl1UYQTIvU+uK3AG5e32htRv89ggC+0KOUS23WQIhlUrf7YT09P9yOWNEbGyPs6s8FkcD1hJZhdqD4O6jPX1ZBTS7/k5wD/N9m189KFZBrCaw9c25eNQdliiVHkVc/ST1OPswUvbwaHH6w5zZx6pLsL/52tvBedoDgwK6vftOM8c2aahJYwyJx1d8MI2PkK2xb0eri/qBlBsQ9BuYIqBFvNVtl2/ykc6OQ6rdUi+YN05fehYLtWYHeJ7aKG8IGyMPvWCk86Rqh/WYiImGtrVYyaBzeaTwsaRWtOJozqIlec5DBJZAbCquEZMrLubYrucN9o0TKMX3Wh759PHLFJHFmLs/5p2sLcDE0rXtm+BI5ur/aJxfaeyVXITyTgb/us5sCMT/5/Va3Ymzn89R28vvqWrK4dKfg41Zk0RP2LZET4k+1mOP75jT4dbMY0+Y83k11qvhpVsVulp5M7H+lzXSUEt51WhRLc37+YkGD3Zaao0QiLSJj+Rg9Ahzs00ANFDnLpXDjJ0QI8oIh4gTTzLyrQjhS4vBAQdIZrkV3oimjwXIWgplfxaalSMMZpMoij5Tl1rhtkGfGUe5HtXGNsYQbUUUYd0Oqg7r7cLOJVo=
deploy:
  provider: npm
  email: kei.itof@gmail.com
  api_key:
    secure: nIOh6MzYuCEHUXe16H0bi1vjjfmgeWrQJxonO2wFXcrvcm7hb/Y9exTFgZ53dCsTmkBzXJJ2RlVsriUhTWNFp2F2IrtLc2BFFORA6EFyGqrAEibL+lOiPdARvcqu2COd2yRsrBF+LaqugySkWfb3fv/evluBBr+29ZmUZYlQ7x523EafBEatwkZb2TngIaCCfjSZKn2Oget+C+GhOncZlxtNUr1SIBzk1fiazxtOTWSKnMC+/c6vYBEoGwhVGbkbK6cYIBURlTDXb6yw2Snu/7n1euGrA60/ZUq00X09HcuwfHXRWhwhPm32eboccSAiQCbInif1bdYMh23UfCE2F3kKxC9qN5dc+1NJqdRBKYHSTLHlUQMN/2YBUEV3hZGhorohW2jwpGdftJY9eB1iAQTlcXF62/hdEnkJ9oHqqagX6iOvquMLP/MdbceI37Yqm8EWHgvIocWwIJbsujTKj/iciaNLJdF1C8SRe9XI1hW8EJ2SoApzWueNtFDSNxaRx1BcGZ7pwQkXg8HvK4jpiKC5hMOt67cfIbmP9LPO7MkY7Vrn4Sb+91IPctXg4YaE9rOWHAq2kMzyPA8VryBtZAWuYSk7AB7EAUMOf80LGKi6Je1EqzFXimF4O2q+UDPt4+cp0r5l9oYEb4TzY6iC/UHs+b3GQpKqZl9GDsfAUbs=
  on:
    tags: true
    branch: master
    repo: kei-ito/j0
