language: java
jdk:
  - oraclejdk8
env:
  - BROWSER=phantomjs
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  code_climate: dd662873003f506c468db393bbb2750f5485fa5dbfe537d151c04d2e614d5183
install:
  - export CXX=g++-4.8
  - nvm install stable
  - npm install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5
script:
  - npm test
after_success:
  - npm install -g codeclimate-test-reporter
  - CODECLIMATE_REPO_TOKEN=dd662873003f506c468db393bbb2750f5485fa5dbfe537d151c04d2e614d5183 codeclimate-test-reporter < ./coverage/lcov.info
notifications:
  slack:
    secure: dJr827OKb0wZgq/cX8C06PzxcTho1kyDkD5gtq3FWyN8i+0pa52jV22MHYMhbKl/Er7Tl1UYQTIvU+uK3AG5e32htRv89ggC+0KOUS23WQIhlUrf7YT09P9yOWNEbGyPs6s8FkcD1hJZhdqD4O6jPX1ZBTS7/k5wD/N9m189KFZBrCaw9c25eNQdliiVHkVc/ST1OPswUvbwaHH6w5zZx6pLsL/52tvBedoDgwK6vftOM8c2aahJYwyJx1d8MI2PkK2xb0eri/qBlBsQ9BuYIqBFvNVtl2/ykc6OQ6rdUi+YN05fehYLtWYHeJ7aKG8IGyMPvWCk86Rqh/WYiImGtrVYyaBzeaTwsaRWtOJozqIlec5DBJZAbCquEZMrLubYrucN9o0TKMX3Wh759PHLFJHFmLs/5p2sLcDE0rXtm+BI5ur/aJxfaeyVXITyTgb/us5sCMT/5/Va3Ymzn89R28vvqWrK4dKfg41Zk0RP2LZET4k+1mOP75jT4dbMY0+Y83k11qvhpVsVulp5M7H+lzXSUEt51WhRLc37+YkGD3Zaao0QiLSJj+Rg9Ahzs00ANFDnLpXDjJ0QI8oIh4gTTzLyrQjhS4vBAQdIZrkV3oimjwXIWgplfxaalSMMZpMoij5Tl1rhtkGfGUe5HtXGNsYQbUUUYd0Oqg7r7cLOJVo=
