import '../Symbol/polyfill';
import '../Array/polyfill';
import '../String/polyfill';
import '../Promise/polyfill';
import '../Map/polyfill';
import '../Set/polyfill';
import '../NodeList/polyfill';
import '../HTMLCollection/polyfill';
import '../NamedNodeMap/polyfill';
import '../URLSearchParams/polyfill';
import '../Headers/polyfill';
import '../fetch/polyfill';
import '../Body/polyfill';
import '../Response/polyfill';
import '../Request/polyfill';
import '../FormData/polyfill';
import '../requestAnimationFrame/polyfill';
import '../cancelAnimationFrame/polyfill';
import {window} from '..';
window.global = window;
